#!/usr/bin/env node

// ============================================================================
// Follow Builders — Prepare Digest
// ============================================================================
// Fetches central feeds and prompts, reads user config, outputs a single JSON
// blob for the LLM to remix into a Chinese digest.
// ============================================================================

import { readFile } from 'fs/promises';
import { existsSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';

const USER_DIR = join(homedir(), '.follow-builders');
const CONFIG_PATH = join(USER_DIR, 'config.json');

const scriptDir = decodeURIComponent(new URL('.', import.meta.url).pathname);
const DATA_DIR = join(scriptDir, '..', 'data');

// Local data files (generated by fetch-feeds.js)
const LOCAL_FEED_X = join(DATA_DIR, 'feed-x.json');
const LOCAL_FEED_PODCASTS = join(DATA_DIR, 'feed-podcasts.json');
const LOCAL_FEED_BLOGS = join(DATA_DIR, 'feed-blogs.json');

// Remote fallback URLs
const FEED_X_URL = 'https://raw.githubusercontent.com/zarazhangrui/follow-builders/main/feed-x.json';
const FEED_PODCASTS_URL = 'https://raw.githubusercontent.com/zarazhangrui/follow-builders/main/feed-podcasts.json';
const FEED_BLOGS_URL = 'https://raw.githubusercontent.com/zarazhangrui/follow-builders/main/feed-blogs.json';

const PROMPT_FILES = [
  'summarize-podcast.md',
  'summarize-tweets.md',
  'summarize-blogs.md',
  'digest-intro.md'
];

async function fetchJSON(url) {
  const res = await fetch(url);
  if (!res.ok) return null;
  return res.json();
}

async function loadLocalOrRemote(localPath, remoteUrl) {
  // Prefer local data (generated by fetch-feeds.js)
  if (existsSync(localPath)) {
    try {
      const data = JSON.parse(await readFile(localPath, 'utf-8'));
      return data;
    } catch (err) {
      // Fall through to remote
    }
  }
  // Fallback to remote
  return fetchJSON(remoteUrl);
}

async function main() {
  const errors = [];

  // 1. Read user config
  let config = { language: 'zh', delivery: { method: 'telegram' } };
  if (existsSync(CONFIG_PATH)) {
    try {
      config = JSON.parse(await readFile(CONFIG_PATH, 'utf-8'));
    } catch (err) {
      errors.push(`Could not read config: ${err.message}`);
    }
  }

  // 2. Load feeds: local data first (from fetch-feeds.js), fallback to remote
  const [feedX, feedPodcasts, feedBlogs] = await Promise.all([
    loadLocalOrRemote(LOCAL_FEED_X, FEED_X_URL),
    loadLocalOrRemote(LOCAL_FEED_PODCASTS, FEED_PODCASTS_URL),
    loadLocalOrRemote(LOCAL_FEED_BLOGS, FEED_BLOGS_URL)
  ]);

  if (!feedX) errors.push('Could not fetch tweet feed');
  if (!feedPodcasts) errors.push('Could not fetch podcast feed');
  if (!feedBlogs) errors.push('Could not fetch blog feed');

  // 3. Load prompts: user custom > local
  const prompts = {};
  const scriptDir = decodeURIComponent(new URL('.', import.meta.url).pathname);
  const localPromptsDir = join(scriptDir, '..', 'prompts');
  const userPromptsDir = join(USER_DIR, 'prompts');

  for (const filename of PROMPT_FILES) {
    const key = filename.replace('.md', '').replace(/-/g, '_');
    const userPath = join(userPromptsDir, filename);
    const localPath = join(localPromptsDir, filename);

    if (existsSync(userPath)) {
      prompts[key] = await readFile(userPath, 'utf-8');
    } else if (existsSync(localPath)) {
      prompts[key] = await readFile(localPath, 'utf-8');
    } else {
      errors.push(`Could not load prompt: ${filename}`);
    }
  }

  // 4. Build output
  const output = {
    status: 'ok',
    generatedAt: new Date().toISOString(),
    config: {
      language: config.language || 'zh',
      delivery: config.delivery || { method: 'telegram' }
    },
    podcasts: feedPodcasts?.podcasts || [],
    x: feedX?.x || [],
    blogs: feedBlogs?.blogs || [],
    stats: {
      podcastEpisodes: feedPodcasts?.podcasts?.length || 0,
      xBuilders: feedX?.x?.length || 0,
      totalTweets: (feedX?.x || []).reduce((sum, a) => sum + a.tweets.length, 0),
      blogPosts: feedBlogs?.blogs?.length || 0,
      feedGeneratedAt: feedX?.generatedAt || feedPodcasts?.generatedAt || feedBlogs?.generatedAt || null
    },
    prompts,
    errors: errors.length > 0 ? errors : undefined
  };

  console.log(JSON.stringify(output, null, 2));
}

main().catch(err => {
  console.error(JSON.stringify({ status: 'error', message: err.message }));
  process.exit(1);
});
